name: cross-platform build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cross-platform-build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wine python3-pip
          python3 -m pip install --upgrade pip
          pip install -r src/requirements.txt

      # Build for Linux
      - name: build for Linux
        run: |
          pyinstaller --onefile --name=dots-linux src/main.py

      # Build for Windows using Wine
      - name: build for Windows
        run: |
          pyinstaller --onefile --name=dots-windows.exe src/main.py

      # Build for macOS using dockcross
      - name: build for macOS
        run: |
          curl -fsSL https://github.com/dockcross/dockcross/raw/master/macos > ./dockcross-macos
          chmod +x ./dockcross-macos
          ./dockcross-macos bash -c "pip install -r src/requirements.txt && pyinstaller --onefile --name=dots-macos src/main.py"

      # Upload artifacts
      - name: upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cross-platform-build
          path: dist/*
