name: build and lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: analyze code with pylint
        run: |
          pylint $(git ls-files '*.py') --disable missing-module-docstring,missing-function-docstring,missing-class-docstring,invalid-name,too-many-locals,too-many-arguments,too-many-branches,too-many-statements,too-many-instance-attributes,too-few-public-methods,too-many-public-methods,too-many-return-statements,too-many-nested-blocks,import-error,wildcard-import,unused-wildcard-import,consider-using-enumerate,consider-using-in,consider-using-get,consider-using-dict-comprehension,consider-using-set-comprehension,consider-using-generator,consider-using-sys-exit,consider-using-join,consider-using-ternary,too-many-positional-arguments,dangerous-default-value,possibly-used-before-assignment,consider-using-dict-items,bare-except

  build-linux:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          python3 -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: build for linux
        run: |
          pyinstaller --onefile --name=dots-linux src/main.py

  build-windows:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wine python3-pip
          python3 -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: build for windows
        run: |
          pyinstaller --onefile --name=dots-windows.exe src/main.py

  build-macos:
    needs: lint
    runs-on: macos-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: 3.13

      - name: install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r src/requirements.txt
          pip install pyinstaller  # Ensure pyinstaller is installed in the virtual environment

      - name: build for macos
        run: |
          source venv/bin/activate
          pyinstaller --onefile --name=dots-macos src/main.py

  upload-artifacts:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cross-platform-build
          path: dist/
