name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --disable line-too-long --disable missing-module-docstring --disable missing-function-docstring --disable missing-class-docstring --disable invalid-name --disable too-many-arguments --disable too-many-locals --disable too-many-branches --disable too-many-statements --disable too-many-instance-attributes --disable too-many-public-methods --disable too-few-public-methods --disable too-many-return-statements --disable
